---
output: html_notebook
---

# Intro
data science를 공부하며 나온 내용을 전체적으로 정리하는 폴더  
개괄적인 내용은 README에 정리함

---

# tip
- 지도 학습 vs 비지도 학습
일반적인 경우에는 지도 학습이 좀 더 효과적임

- 비정형 데이터 잘 분석하기
그냥 분석하면 너무 데이터가 많아서 힘듬  
비정형 데이터를 효과적으로 분석하려면, 특질점(feature)을 뽑아내야 한다.  
ex) 이미지 데이터에서 모든 pixel을 분석하는게 아니라, 명암차이에 따른 엣지를 찾아서 feature로 만듬  

- 알고리즘 사용 방법
해당 알고리즘의 이름으로 구글 검색해서 첫 페이지에 나오는 패키지 가져다 쓰면 됨

- 특정 패키지들은 쉽게 익힐 수 있게 하는 샘플 데이터를 같이 첨부한다

- 거리 계산을 하는 알고리즘에서 단위가 다르면 영향력의 차이가 발생하므로, 각 단위를 정규화 해야 한다

## 데이터의 실 응용 
- 오프라인 매장 A/B test
여러곳에서 같이 잘 팔리는 아이템들을 가깝게 놓고,
다른 매장 여러 곳은 멀게 놓아서 3개월간 매출 추이를 살핌 (우유와 콘 프로스트)
멀리 놓아서 동선을 길게 하여 충돌 구매를 유도 할 수도 있음
  
- 아마존의 패키지 (item-based), 아래 추천 (collaborative filtering)
아마존에서 패키지로 추천 하는 아이템을 합쳐서, 단독으로 사는 것보다 할인해줌  

- 주식 포트폴리오 만들 때, 군집화로 비슷한 주식들을 모아서 작업

- 뭔가 비교를 하는 작업에서, 비슷한 그룹을 찾아내 줌
ex) 경쟁사와의 특허 문서 분석을 통한 장단점 파악

### 회귀 분석
- 보험 사기 여부 예측
- 이탈 유저 예측
- 불량 예측

---

# 구분
## 학습 목적에 따른 구분
- 분류
지도학습, y^이 명목형 변수가 나올때 사용

- 군집화
비지도학습

- 연관 규칙
비지도학습

- 회귀분석 == 예측
y^이 연속형 변수가 나올때, 경우의 수가 무한하게 나올 수 있으므로 회귀로 처리함

- 이상치 탐지 
Anomaly Detaection  
정상과 비정상을 찾아내는 분류문제  
일반 분류와 따로 구분된 이유는 이상치 데이터가 매우 소량이라 학습하기 힘들어서,
잘 학습하는 방법론이 존재함

---

## 데이터의 형태에 따른 구분
- 정형 데이터
structured Data  
명목형, 숫자로 표현되는 데이터

- 비정형 데이터 
Unstructured Data  
이미지/음성/텍스트로 숫자가 아닌 형태의 정보가 구조화되지 않은 형태로 존재

---

## 모델 업데이트와 학습의 최종 목적에 따른 구분
- static : 한번에. 자주 쓰는 기법. 데이터가 업데이트 되면 매번 분석 다시해야 함
- Incremental : 부분적으로..
47page 참고

---

# 단어
- 여러 분야의 사람들이 들어와서 한 개념을 설명하는 이름이 여러개

## 변수
- variable == feature == attribute

### X
- 독립변수 == 예측 변수 == 인풋 변수 == 원인

### Y
- 종속 변수 == 반응변수 == 아웃풋 변수 == 결과

## 데이터
- 객체 == data == 관측치

## 파라미터
== 하이퍼 파라미터  
유저가 설정해야 하는 전제 조건, 수치값

## training data
== 학습 데이터 == learning 데이터 == training set?

## testing data
== 테스트 데이터 == training set?

## 상관관계
- 양의 상관관계 == 비례
- 음의 상관관계 == 반비례

---

# 정의
## 머신러닝
인간이 개발한 알고리즘을 컴퓨터 언어를 통해 기계에게 학습시키는 행위

## 모델링
 y = f(x) 에서 입력/출력을 알거나 모를때, f(x)를 찾아라
 
## 연속형 데이터 continueous
숫자로 표현할 수 있는 것 

## 범주형 데이터 factor
== 요인형 == 명목형  
숫자로 표현 할 수 없는 데이터  
숫자로 표현한다 해도 양적 비교를 할 수 없음  
boolen, 

---

# 관련 언어
- SAS
- R
- Python

# 데이터 분석 툴
- SAS
일반적으로는 기존의 플랫폼하고 연동하기 힘듬

- WEKA
꽁짜  
쓰기 편하지만 강력하진 않음   
SAS/ MATLAB 에 익숙해지기 전에 툴에 대한 이해를 하기에 좋음

- MATLAB

---

# 연습용 데이터 셋 구하는 곳
- [UCI KDD archive](http://archive.ics.uci.edu/ml) : 설명이 상세하고, 다른 사람 코드가 오픈되어 있음
- [KDnuggets datasets](http://www.kDnuggets.com/datasets/index.html)
- [Wikipedia: Database downlad](https://ko.wikipedia.org/wiki/%EC%9C%84%ED%82%A4%EB%B0%B1%EA%B3%BC:%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4_%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C)
- 

# 참고 자료
- MIT Technology Review

